### PR TITLE
.NET Reference assemblies v4.7.2 

### LINKED ISSUE #8657: .NET 4.7.2 reference assemblies
The 4.7.2 version is out and we need to add it as well. This should be done together with #7859

We keep the reference assemblies in separate repo https://github.com/mono/reference-assemblies

## Steps required
- [x] Add new reference assemblies
- [x] Bump submodule reference in Mono
- [x] Add new framework to mcs/tools/xbuild/frameworks and update Makefile to ship it

### PR DESCRIPTION
**Pull request by henricm**
This PR fixes mono/mono#8657 by adding 4.7.2 reference assemblies to Mono.

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
Looks great! Thanks for keeping the copy and update in separate commits, it was perfect for reviewing :)

**Comment by henricm** [comment]
Thanks, and thanks for the help along the way!

**Comment by kirill-gerasimenko** [comment]
Hi, this is great! When do you think this can be released?

**Comment by henricm** [comment]
There are a few steps left to get it into mono as described here: https://github.com/mono/mono/issues/8657
Shouldn't take too long. However, I don't know the exact release schedule once it's fully been merged.

**Comment by marek-safar** [comment]
We'll backport it to Mono 5.20 release

**Comment by achilles08** [comment]
is it possible to backport this to 5.18 release?

**Comment by akoeplinger** [comment]
We backported it to the mono 2018-08 branch (== Mono 5.18.0.208) with https://github.com/mono/mono/pull/11733.

**Comment by achilles08** [comment]
When that could be released as stable, just to have an idea

**Comment by marek-safar** [comment]
Pretty soon (probably before the end of November)

**Comment by achilles08** [comment]
> Pretty soon (probably before the end of November)

not demanding but any update on this

**Pull request merged**
