### PR TITLE
Update binary-reference-assemblies

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by kjpou1 — APPROVED** [review]
This looks good to me but do not merge yet

**Review by kjpou1 — COMMENTED** [review]
Do not merge yet.  Waiting on draft PR https://github.com/mono/mono/pull/19260

**Comment by marek-safar** [comment]
This should not be needed as the code will be included directly

**Comment by pranavkm** [comment]
> This should not be needed as the code will be included directly

@marek-safar could you elaborate what this means?

**Comment by marek-safar** [comment]
There should be no dependency from System.Net.Http to System.Net.Http.WebAssemblyHttpHandler, therefore, the change is not needed.

**Pull request merged**
